FROM ubuntu
COPY sp1.sh .
RUN chmod ugo+x sp1.sh
RUN apt-get -qq update
RUN apt-get -qq install genisoimage > genisoimage_install_logs
RUN apt-get -qq install p7zip-full > 7zip_install_logs
CMD sh sp1.sh
